<div style="width:1000 px">

<div style="float:right; width:98 px; height:98px;">
<img src="https://raw.githubusercontent.com/Unidata/MetPy/master/src/metpy/plots/_static/unidata_150x150.png" alt="Unidata Logo" style="height: 98px;">
</div>

<h1>XArray & CF Introduction</h1>

<div style="clear:both"></div>
</div>

<hr style="height:2px;">

<div style="float:right; width:250 px"><img src="http://xarray.pydata.org/en/stable/_static/dataset-diagram-logo.png" alt="NumPy Logo" style="height: 250px;"></div>

### Questions
1. What is XArray?
2. How does XArray fit in with Numpy and Pandas?
3. What is the CF convention and how do we use it with Xarray?

### Objectives
1. Create a `DataArray`.
2. Open netCDF data using XArray
3. Subset the data.
4. Write a CF-compliant netCDF file

## XArray

XArray expands on the capabilities on NumPy arrays, providing a lot of streamlined data manipulation. It is similar in that respect to Pandas, but whereas Pandas excels at working with tabular data, XArray is focused on N-dimensional arrays of data (i.e. grids). Its interface is based largely on the netCDF data model (variables, attributes, and dimensions), but it goes beyond the traditional netCDF interfaces to provide functionality similar to netCDF-java's Common Data Model (CDM). 

### `DataArray`

The `DataArray` is one of the basic building blocks of XArray. It provides a NumPy ndarray-like object that expands to provide two critical pieces of functionality:

1. Coordinate names and values are stored with the data, making slicing and indexing much more powerful
2. It has a built-in container for attributes

In [1]:
# Convention for import to get shortened namespace
import numpy as np
import xarray as xr

In [2]:
# Create some sample "temperature" data
data = 283 + 5 * np.random.randn(5, 3, 4)
data

array([[[288.11371613, 284.38269056, 280.68733277, 279.08252948],
        [280.7079052 , 284.82190397, 291.69401677, 276.35331753],
        [283.68730153, 291.15096932, 286.50463856, 283.28474196]],

       [[288.49959349, 278.53439317, 278.36660052, 275.33654394],
        [294.30178766, 276.44572187, 280.79737482, 274.83234774],
        [276.61754208, 285.70790413, 285.43863034, 268.30343696]],

       [[282.92786289, 284.7024919 , 285.85984187, 278.28154137],
        [276.90722293, 283.30514309, 278.58323263, 282.52107438],
        [288.29282508, 287.00614678, 280.83815473, 280.85687943]],

       [[274.20532348, 287.7264625 , 280.79736103, 280.7895651 ],
        [279.84667456, 282.85555574, 289.90248032, 284.44834698],
        [278.53375057, 283.20685189, 286.51958674, 290.29519528]],

       [[291.33479493, 279.1814093 , 283.14737608, 279.33155298],
        [283.0214905 , 274.60769143, 288.71124999, 284.69596576],
        [290.47955487, 280.37399521, 288.28499174, 291.6492603 ]]])

Here we create a basic `DataArray` by passing it just a numpy array of random data. Note that XArray generates some basic dimension names for us.

In [3]:
temp = xr.DataArray(data)
temp

<xarray.DataArray (dim_0: 5, dim_1: 3, dim_2: 4)>
array([[[288.11371613, 284.38269056, 280.68733277, 279.08252948],
        [280.7079052 , 284.82190397, 291.69401677, 276.35331753],
        [283.68730153, 291.15096932, 286.50463856, 283.28474196]],

       [[288.49959349, 278.53439317, 278.36660052, 275.33654394],
        [294.30178766, 276.44572187, 280.79737482, 274.83234774],
        [276.61754208, 285.70790413, 285.43863034, 268.30343696]],

       [[282.92786289, 284.7024919 , 285.85984187, 278.28154137],
        [276.90722293, 283.30514309, 278.58323263, 282.52107438],
        [288.29282508, 287.00614678, 280.83815473, 280.85687943]],

       [[274.20532348, 287.7264625 , 280.79736103, 280.7895651 ],
        [279.84667456, 282.85555574, 289.90248032, 284.44834698],
        [278.53375057, 283.20685189, 286.51958674, 290.29519528]],

       [[291.33479493, 279.1814093 , 283.14737608, 279.33155298],
        [283.0214905 , 274.60769143, 288.71124999, 284.69596576],
        [290.47955487, 280.37399521, 288.28499174, 291.6492603 ]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

We can also pass in our own dimension names:

In [4]:
temp = xr.DataArray(data, dims=['time', 'lat', 'lon'])
temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[288.11371613, 284.38269056, 280.68733277, 279.08252948],
        [280.7079052 , 284.82190397, 291.69401677, 276.35331753],
        [283.68730153, 291.15096932, 286.50463856, 283.28474196]],

       [[288.49959349, 278.53439317, 278.36660052, 275.33654394],
        [294.30178766, 276.44572187, 280.79737482, 274.83234774],
        [276.61754208, 285.70790413, 285.43863034, 268.30343696]],

       [[282.92786289, 284.7024919 , 285.85984187, 278.28154137],
        [276.90722293, 283.30514309, 278.58323263, 282.52107438],
        [288.29282508, 287.00614678, 280.83815473, 280.85687943]],

       [[274.20532348, 287.7264625 , 280.79736103, 280.7895651 ],
        [279.84667456, 282.85555574, 289.90248032, 284.44834698],
        [278.53375057, 283.20685189, 286.51958674, 290.29519528]],

       [[291.33479493, 279.1814093 , 283.14737608, 279.33155298],
        [283.0214905 , 274.60769143, 288.71124999, 284.69596576],
        [290.47955487, 280.37399521, 288.28499174, 291.6492603 ]]])
Dimensions without coordinates: time, lat, lon

This is already improved upon from a numpy array, because we have names for each of the dimensions (or axes in NumPy parlance). Even better, we can take arrays representing the values for the coordinates for each of these dimensions and associate them with the data when we create the `DataArray`.

In [5]:
# Use pandas to create an array of datetimes
import pandas as pd
times = pd.date_range('2018-01-01', periods=5)
times

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

In [6]:
# Sample lon/lats
lons = np.linspace(-120, -60, 4)
lats = np.linspace(25, 55, 3)

When we create the `DataArray` instance, we pass in the arrays we just created:

In [7]:
temp = xr.DataArray(data, coords=[times, lats, lons], dims=['time', 'lat', 'lon'])
temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[288.11371613, 284.38269056, 280.68733277, 279.08252948],
        [280.7079052 , 284.82190397, 291.69401677, 276.35331753],
        [283.68730153, 291.15096932, 286.50463856, 283.28474196]],

       [[288.49959349, 278.53439317, 278.36660052, 275.33654394],
        [294.30178766, 276.44572187, 280.79737482, 274.83234774],
        [276.61754208, 285.70790413, 285.43863034, 268.30343696]],

       [[282.92786289, 284.7024919 , 285.85984187, 278.28154137],
        [276.90722293, 283.30514309, 278.58323263, 282.52107438],
        [288.29282508, 287.00614678, 280.83815473, 280.85687943]],

       [[274.20532348, 287.7264625 , 280.79736103, 280.7895651 ],
        [279.84667456, 282.85555574, 289.90248032, 284.44834698],
        [278.53375057, 283.20685189, 286.51958674, 290.29519528]],

       [[291.33479493, 279.1814093 , 283.14737608, 279.33155298],
        [283.0214905 , 274.60769143, 288.71124999, 284.69596576],
        [290.47955487, 280.37399521, 288.28499174, 291.6492603 ]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

...and we can also set some attribute metadata:

In [8]:
temp.attrs['units'] = 'kelvin'
temp.attrs['standard_name'] = 'air_temperature'

temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[288.11371613, 284.38269056, 280.68733277, 279.08252948],
        [280.7079052 , 284.82190397, 291.69401677, 276.35331753],
        [283.68730153, 291.15096932, 286.50463856, 283.28474196]],

       [[288.49959349, 278.53439317, 278.36660052, 275.33654394],
        [294.30178766, 276.44572187, 280.79737482, 274.83234774],
        [276.61754208, 285.70790413, 285.43863034, 268.30343696]],

       [[282.92786289, 284.7024919 , 285.85984187, 278.28154137],
        [276.90722293, 283.30514309, 278.58323263, 282.52107438],
        [288.29282508, 287.00614678, 280.83815473, 280.85687943]],

       [[274.20532348, 287.7264625 , 280.79736103, 280.7895651 ],
        [279.84667456, 282.85555574, 289.90248032, 284.44834698],
        [278.53375057, 283.20685189, 286.51958674, 290.29519528]],

       [[291.33479493, 279.1814093 , 283.14737608, 279.33155298],
        [283.0214905 , 274.60769143, 288.71124999, 284.69596576],
        [290.47955487, 280.37399521, 288.28499174, 291.6492603 ]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

Notice what happens if we perform a mathematical operaton with the `DataArray`: the coordinate values persist, but the attributes are lost. This is done because it is very challenging to know if the attribute metadata is still correct or appropriate after arbitrary arithmetic operations.

In [9]:
# For example, convert Kelvin to Celsius
temp - 273.15

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[14.96371613, 11.23269056,  7.53733277,  5.93252948],
        [ 7.5579052 , 11.67190397, 18.54401677,  3.20331753],
        [10.53730153, 18.00096932, 13.35463856, 10.13474196]],

       [[15.34959349,  5.38439317,  5.21660052,  2.18654394],
        [21.15178766,  3.29572187,  7.64737482,  1.68234774],
        [ 3.46754208, 12.55790413, 12.28863034, -4.84656304]],

       [[ 9.77786289, 11.5524919 , 12.70984187,  5.13154137],
        [ 3.75722293, 10.15514309,  5.43323263,  9.37107438],
        [15.14282508, 13.85614678,  7.68815473,  7.70687943]],

       [[ 1.05532348, 14.5764625 ,  7.64736103,  7.6395651 ],
        [ 6.69667456,  9.70555574, 16.75248032, 11.29834698],
        [ 5.38375057, 10.05685189, 13.36958674, 17.14519528]],

       [[18.18479493,  6.0314093 ,  9.99737608,  6.18155298],
        [ 9.8714905 ,  1.45769143, 15.56124999, 11.54596576],
        [17.32955487,  7.22399521, 15.13499174, 18.4992603 ]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

### Selection
We can use the `.sel` method to select portions of our data based on these coordinate values, rather than using indices (this is similar to the CDM).

In [10]:
temp.sel(time='2018-01-02')

<xarray.DataArray (lat: 3, lon: 4)>
array([[288.49959349, 278.53439317, 278.36660052, 275.33654394],
       [294.30178766, 276.44572187, 280.79737482, 274.83234774],
       [276.61754208, 285.70790413, 285.43863034, 268.30343696]])
Coordinates:
    time     datetime64[ns] 2018-01-02
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

`.sel` has the flexibility to also perform nearest neighbor sampling, taking an optional tolerance:

In [11]:
from datetime import timedelta
temp.sel(time='2018-01-07', method='nearest', tolerance=timedelta(days=2))

<xarray.DataArray (lat: 3, lon: 4)>
array([[291.33479493, 279.1814093 , 283.14737608, 279.33155298],
       [283.0214905 , 274.60769143, 288.71124999, 284.69596576],
       [290.47955487, 280.37399521, 288.28499174, 291.6492603 ]])
Coordinates:
    time     datetime64[ns] 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

<div class="alert alert-success">
    <b>EXERCISE</b>:
    
.interp() works similarly to .sel(). Using .interp(), get an interpolated time series "forecast" for Boulder (40°N, 105°W) or your favorite latitude/longitude location. (Documentation for interp <a href="http://xarray.pydata.org/en/stable/interpolation.html">here</a>).
</div>

In [12]:
# YOUR CODE GOES HERE

<div class="alert alert-info">
    <b>SOLUTION</b>
</div>

In [13]:
# %load solutions/interp_solution.py

### Slicing with Selection

In [14]:
temp.sel(time=slice('2018-01-01', '2018-01-03'), lon=slice(-110, -70), lat=slice(25, 45))

<xarray.DataArray (time: 3, lat: 2, lon: 2)>
array([[[284.38269056, 280.68733277],
        [284.82190397, 291.69401677]],

       [[278.53439317, 278.36660052],
        [276.44572187, 280.79737482]],

       [[284.7024919 , 285.85984187],
        [283.30514309, 278.58323263]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 2018-01-03
  * lat      (lat) float64 25.0 40.0
  * lon      (lon) float64 -100.0 -80.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

### `.loc`

All of these operations can also be done within square brackets on the `.loc` attribute of the `DataArray`. This permits a much more numpy-looking syntax, though you lose the ability to specify the names of the various dimensions. Instead, the slicing must be done in the correct order.

In [15]:
# As done above
temp.loc['2018-01-02']

<xarray.DataArray (lat: 3, lon: 4)>
array([[288.49959349, 278.53439317, 278.36660052, 275.33654394],
       [294.30178766, 276.44572187, 280.79737482, 274.83234774],
       [276.61754208, 285.70790413, 285.43863034, 268.30343696]])
Coordinates:
    time     datetime64[ns] 2018-01-02
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [16]:
temp.loc['2018-01-01':'2018-01-03', 25:45, -110:-70]

<xarray.DataArray (time: 3, lat: 2, lon: 2)>
array([[[284.38269056, 280.68733277],
        [284.82190397, 291.69401677]],

       [[278.53439317, 278.36660052],
        [276.44572187, 280.79737482]],

       [[284.7024919 , 285.85984187],
        [283.30514309, 278.58323263]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 2018-01-03
  * lat      (lat) float64 25.0 40.0
  * lon      (lon) float64 -100.0 -80.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [17]:
# This *doesn't* work however:
#temp.loc[-110:-70, 25:45,'2018-01-01':'2018-01-03']

## Opening netCDF data
With its close ties to the netCDF data model, XArray also supports netCDF as a first-class file format. This means it has easy support for opening netCDF datasets, so long as they conform to some of XArray's limitations (such as 1-dimensional coordinates).

In [18]:
# Open sample North American Reanalysis data in netCDF format
ds = xr.open_dataset('../../data/NARR_19930313_0000.nc')
ds

<xarray.Dataset>
Dimensions:                       (time1: 1, isobaric1: 29, y: 119, x: 268)
Coordinates:
  * time1                         (time1) datetime64[ns] 1993-03-13
  * isobaric1                     (isobaric1) float32 100.0 125.0 ... 1e+03
  * y                             (y) float32 -3.117e+03 -3.084e+03 ... 714.1
  * x                             (x) float32 -3.324e+03 ... 5.343e+03
Data variables:
    u-component_of_wind_isobaric  (time1, isobaric1, y, x) float32 ...
    LambertConformal_Projection   int32 ...
    lat                           (y, x) float64 ...
    lon                           (y, x) float64 ...
    Geopotential_height_isobaric  (time1, isobaric1, y, x) float32 ...
    v-component_of_wind_isobaric  (time1, isobaric1, y, x) float32 ...
    Temperature_isobaric          (time1, isobaric1, y, x) float32 ...
Attributes:
    Originating_or_generating_Center:     US National Weather Service, Nation...
    Originating_or_generating_Subcenter:  North American Regional Reanalysis ...
    GRIB_table_version:                   0,131
    Generating_process_or_model:          North American Regional Reanalysis ...
    Conventions:                          CF-1.6
    history:                              Read using CDM IOSP GribCollection v3
    featureType:                          GRID
    History:                              Translated to CF-1.0 Conventions by...
    geospatial_lat_min:                   10.753308882144761
    geospatial_lat_max:                   46.8308828962289
    geospatial_lon_min:                   -153.88242040519995
    geospatial_lon_max:                   -42.666108129242815

In [19]:
!ls ../../data

air.mon.mean.v501.nc
CMIP.HAMMOZ-Consortium.MPI-ESM-1-2-HAM.historical.Amon.gn.nc
CMIP.HAMMOZ-Consortium.MPI-ESM-1-2-HAM.historical.SImon.gn.nc
CMIP.MPI-M.MPI-ESM1-2-HR.historical.Amon.gn.nc
CMIP.MPI-M.MPI-ESM1-2-HR.historical.SImon.gn.nc
CMIP.MPI-M.MPI-ESM1-2-LR.historical.Amon.gn.nc
CMIP.MPI-M.MPI-ESM1-2-LR.historical.SImon.gn.nc
CMIP.NCAR.CESM2-FV2.historical.Amon.gn.nc
CMIP.NCAR.CESM2-FV2.historical.SImon.gn.nc
CMIP.NCAR.CESM2.historical.Amon.gn.nc
CMIP.NCAR.CESM2.historical.SImon.gn.nc
CMIP.NCAR.CESM2-WACCM-FV2.historical.Amon.gn.nc
CMIP.NCAR.CESM2-WACCM-FV2.historical.SImon.gn.nc
CMIP.NCAR.CESM2-WACCM.historical.Amon.gn.nc
CMIP.NCAR.CESM2-WACCM.historical.SImon.gn.nc
CMIP.NCC.NorESM2-MM.historical.Amon.gm.nc
CMIP.NCC.NorESM2-MM.historical.SImon.gn.nc
DWD_regional_averages_txbs_year_hot_days.txt
MET9_IR108_cosmode_0909210000.grb2
NARR_19930313_0000.nc
pr.dat
precip_day01.nc
precip_day02.nc
precip_day03.nc
rectilinear_grid_2D.nc
species_not_real.csv
sst.mnmean.nc
tsurf.nc
World_Nat

This returns a `Dataset` object, which is a container that contains one or more `DataArray`s, which can also optionally share coordinates. We can then pull out individual fields:

In [20]:
ds.isobaric1

<xarray.DataArray 'isobaric1' (isobaric1: 29)>
array([ 100.,  125.,  150.,  175.,  200.,  225.,  250.,  275.,  300.,  350.,
        400.,  450.,  500.,  550.,  600.,  650.,  700.,  725.,  750.,  775.,
        800.,  825.,  850.,  875.,  900.,  925.,  950.,  975., 1000.],
      dtype=float32)
Coordinates:
  * isobaric1  (isobaric1) float32 100.0 125.0 150.0 175.0 ... 950.0 975.0 1e+03
Attributes:
    units:                   hPa
    long_name:               Isobaric surface
    positive:                down
    Grib_level_type:         100
    _CoordinateAxisType:     Pressure
    _CoordinateZisPositive:  down

or

In [21]:
ds['isobaric1']

<xarray.DataArray 'isobaric1' (isobaric1: 29)>
array([ 100.,  125.,  150.,  175.,  200.,  225.,  250.,  275.,  300.,  350.,
        400.,  450.,  500.,  550.,  600.,  650.,  700.,  725.,  750.,  775.,
        800.,  825.,  850.,  875.,  900.,  925.,  950.,  975., 1000.],
      dtype=float32)
Coordinates:
  * isobaric1  (isobaric1) float32 100.0 125.0 150.0 175.0 ... 950.0 975.0 1e+03
Attributes:
    units:                   hPa
    long_name:               Isobaric surface
    positive:                down
    Grib_level_type:         100
    _CoordinateAxisType:     Pressure
    _CoordinateZisPositive:  down

`Dataset`s also support much of the same subsetting operations as `DataArray`, but will perform the operation on all data:

In [22]:
ds_1000 = ds.sel(isobaric1=1000.0)
ds_1000

<xarray.Dataset>
Dimensions:                       (time1: 1, y: 119, x: 268)
Coordinates:
  * time1                         (time1) datetime64[ns] 1993-03-13
    isobaric1                     float32 1e+03
  * y                             (y) float32 -3.117e+03 -3.084e+03 ... 714.1
  * x                             (x) float32 -3.324e+03 ... 5.343e+03
Data variables:
    u-component_of_wind_isobaric  (time1, y, x) float32 ...
    LambertConformal_Projection   int32 0
    lat                           (y, x) float64 17.87 17.96 ... 34.85 34.64
    lon                           (y, x) float64 -135.0 -134.8 ... -43.13 -42.91
    Geopotential_height_isobaric  (time1, y, x) float32 ...
    v-component_of_wind_isobaric  (time1, y, x) float32 ...
    Temperature_isobaric          (time1, y, x) float32 ...
Attributes:
    Originating_or_generating_Center:     US National Weather Service, Nation...
    Originating_or_generating_Subcenter:  North American Regional Reanalysis ...
    GRIB_table_version:                   0,131
    Generating_process_or_model:          North American Regional Reanalysis ...
    Conventions:                          CF-1.6
    history:                              Read using CDM IOSP GribCollection v3
    featureType:                          GRID
    History:                              Translated to CF-1.0 Conventions by...
    geospatial_lat_min:                   10.753308882144761
    geospatial_lat_max:                   46.8308828962289
    geospatial_lon_min:                   -153.88242040519995
    geospatial_lon_max:                   -42.666108129242815

In [23]:
ds_1000.Temperature_isobaric

<xarray.DataArray 'Temperature_isobaric' (time1: 1, y: 119, x: 268)>
array([[[294.09436, 294.1256 , ..., 298.6725 , 298.71936],
        [294.07874, 294.14124, ..., 298.6256 , 298.5475 ],
        ...,
        [276.86   , 276.84436, ..., 289.11   , 289.01624],
        [277.01624, 276.82874, ..., 289.0475 , 288.96936]]], dtype=float32)
Coordinates:
  * time1      (time1) datetime64[ns] 1993-03-13
    isobaric1  float32 1e+03
  * y          (y) float32 -3.117e+03 -3.084e+03 -3.052e+03 ... 681.6 714.1
  * x          (x) float32 -3.324e+03 -3.292e+03 ... 5.311e+03 5.343e+03
Attributes:
    long_name:           Temperature @ Isobaric surface
    units:               K
    description:         Temperature
    grid_mapping:        LambertConformal_Projection
    Grib_Variable_Id:    VAR_7-15-131-11_L100
    Grib1_Center:        7
    Grib1_Subcenter:     15
    Grib1_TableVersion:  131
    Grib1_Parameter:     11
    Grib1_Level_Type:    100
    Grib1_Level_Desc:    Isobaric surface

### Aggregation operations

Not only can you use the named dimensions for manual slicing and indexing of data, but you can also use it to control aggregation operations, like `sum`:

In [24]:
u_winds = ds['u-component_of_wind_isobaric']
u_winds.std(dim=['x', 'y'])

<xarray.DataArray 'u-component_of_wind_isobaric' (time1: 1, isobaric1: 29)>
array([[ 8.673963 , 10.212325 , 11.556413 , 12.254429 , 13.372146 ,
        15.472462 , 16.091969 , 15.846294 , 15.195834 , 13.936979 ,
        12.93888  , 12.060708 , 10.972139 ,  9.722328 ,  8.853286 ,
         8.257241 ,  7.679721 ,  7.4516497,  7.2352104,  7.039894 ,
         6.883371 ,  6.7821493,  6.7088237,  6.6865997,  6.7247376,
         6.745023 ,  6.6859775,  6.5107226,  5.972262 ]], dtype=float32)
Coordinates:
  * time1      (time1) datetime64[ns] 1993-03-13
  * isobaric1  (isobaric1) float32 100.0 125.0 150.0 175.0 ... 950.0 975.0 1e+03

<div class="alert alert-success">
    <b>EXERCISE</b>:

Using the sample dataset, calculate the mean temperature profile (temperature as a function of pressure) over Colorado within this dataset. For this exercise, consider the bounds of Colorado to be:
     <ul>
         <li>x: -182km to 424km</li>
         <li>y: -1450km to -990km</li>
    </ul>
    
(37°N to 41°N and 102°W to 109°W projected to Lambert Conformal projection coordinates)
</div>

In [25]:
# YOUR CODE GOES HERE

<div class="alert alert-info">
    <b>SOLUTION</b>
</div>

In [26]:
# %load solutions/mean_profile.py

### Resources

There is much more in the XArray library. To learn more, visit the [XArray Documentation](http://xarray.pydata.org/en/stable/index.html)

# Introduction to Climate and Forecasting Metadata Conventions

In order to better enable reproducible data and research, the Climate and Forecasting (CF) metadata convention was created to have proper metadata in atmospheric data files. In the remainder of this notebook, we will introduce the CF data model and discuss some netCDF implementation details to consider when deciding how to write data with CF and netCDF. We will cover gridded data in this notebook, with more in depth examples provided in the full [CF notebook](https://github.com/Unidata/python-workshop/blob/master/notebooks/CF%20Conventions/NetCDF%20and%20CF%20-%20The%20Basics.ipynb). Xarray makes the creation of netCDFs with proper metadata simple and straightforward, so we will use that, instead of the netCDF-Python library.

This assumes a basic understanding of netCDF.

<a name="gridded"></a>
## Gridded Data
Let's say we're working with some numerical weather forecast model output. Let's walk through the steps necessary to store this data in netCDF, using the Climate and Forecasting metadata conventions to ensure that our data are available to as many tools as possible.

To start, let's assume the following about our data:
* It corresponds to forecast three dimensional temperature at several times
* The native coordinate system of the model is on a regular grid that represents the Earth on a Lambert conformal projection.

We'll also go ahead and generate some arrays of data below to get started:

In [27]:
# Import some useful Python tools
from datetime import datetime

# Twelve hours of hourly output starting at 22Z today
start = datetime.utcnow().replace(hour=22, minute=0, second=0, microsecond=0)
times = np.array([start + timedelta(hours=h) for h in range(13)])

# 3km spacing in x and y
x = np.arange(-150, 153, 3)
y = np.arange(-100, 100, 3)

# Standard pressure levels in hPa
press = np.array([1000, 925, 850, 700, 500, 300, 250])

temps = np.random.randn(times.size, press.size, y.size, x.size)

Time coordinates must contain a `units` attribute with a string value with a form similar to `'seconds since 2019-01-06 12:00:00.00'`. 'seconds', 'minutes', 'hours', and 'days' are the most commonly used units for time. Due to the variable length of months and years, they are not recommended.

Before we can write data, we need to first need to convert our list of Python `datetime` instances to numeric values. We can use the `cftime` library to make this easy to convert using the unit string as defined above.

In [28]:
from cftime import date2num
time_units = 'hours since {:%Y-%m-%d 00:00}'.format(times[0])
time_vals = date2num(times, time_units)
time_vals

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

Now we can create the `forecast_time` variable just as we did before for the other coordinate variables:

### Convert arrays into Xarray Dataset

In [29]:
ds = xr.Dataset({'temperature': (['time', 'z', 'y', 'x'], temps, {'units':'Kelvin'})},
                 coords={'x_dist': (['x'], x, {'units':'km'}),
                         'y_dist': (['y'], y, {'units':'km'}),
                         'pressure': (['z'], press, {'units':'hPa'}),
                         'forecast_time': (['time'], times)
                })
ds

<xarray.Dataset>
Dimensions:        (time: 13, z: 7, y: 67, x: 101)
Coordinates:
    x_dist         (x) int64 -150 -147 -144 -141 -138 ... 138 141 144 147 150
    y_dist         (y) int64 -100 -97 -94 -91 -88 -85 -82 ... 83 86 89 92 95 98
    pressure       (z) int64 1000 925 850 700 500 300 250
    forecast_time  (time) datetime64[ns] 2022-08-10T22:00:00 ... 2022-08-11T1...
Dimensions without coordinates: time, z, y, x
Data variables:
    temperature    (time, z, y, x) float64 0.3197 0.6291 ... -1.149 -0.4101

Due to how xarray handles time units, we need to encode the units in the `forecast_time` coordinate.

In [30]:
ds.forecast_time.encoding['units'] = time_units

If we look at our data variable, we can see the units printed out, so they were attached properly!

In [31]:
ds.temperature

<xarray.DataArray 'temperature' (time: 13, z: 7, y: 67, x: 101)>
array([[[[ 0.31966001,  0.62911162,  1.46810581, ...,  0.87515276,
           0.31693765, -0.68455809],
         [ 0.18986965,  0.01840196,  1.42289809, ...,  0.82252125,
          -0.44852218,  0.45830285],
         [-0.59097526,  0.67670655,  1.28691167, ..., -0.23353007,
          -0.03685726,  0.06015763],
         ...,
         [-0.63314104,  1.0627754 ,  0.76806859, ..., -0.37088478,
          -0.1820268 , -0.89601011],
         [-0.8514717 ,  0.49759853, -1.12691574, ...,  0.70800531,
          -0.34981368,  0.40066832],
         [-0.46439381,  0.47530233,  1.18097279, ...,  0.7524677 ,
           0.06313997, -0.1427309 ]],

        [[-0.02283303, -0.09144041,  0.35689833, ...,  0.8239916 ,
           0.60545492, -0.51333928],
         [-0.99362739,  0.72566439,  0.83466609, ..., -1.32078148,
          -0.55641567,  0.80690797],
         [ 0.52498174,  0.29974021,  0.06959481, ...,  0.10632035,
          -0.01577078,  1.26781419],
...
         [-0.19166111,  1.13783231,  1.14830719, ...,  0.34927999,
           0.45713195, -1.48592946],
         [-1.30322075,  2.51739149,  0.81694123, ..., -0.39033119,
           0.62674055,  0.69432544],
         [ 0.1550955 ,  0.12162957,  0.14695446, ..., -0.16959999,
          -0.86542189,  0.02134799]],

        [[ 0.71655814, -1.99119425, -0.71171304, ..., -1.47766572,
          -1.0972982 ,  0.35227179],
         [ 0.51066693, -1.53859285, -1.57714262, ...,  0.71107797,
          -0.26561326,  1.24525168],
         [-0.31004721,  1.92040077, -1.16576846, ..., -0.69747617,
          -0.23262293,  1.02725806],
         ...,
         [ 1.53972641,  0.84477318, -0.25037428, ..., -2.16029206,
           1.70965877, -0.68985913],
         [ 0.32478888,  0.93460854, -0.96472961, ..., -0.43821734,
          -1.37024211, -0.2646514 ],
         [-0.25799393,  0.57621673,  2.0516006 , ...,  0.18359132,
          -1.1489152 , -0.41011924]]]])
Coordinates:
    x_dist         (x) int64 -150 -147 -144 -141 -138 ... 138 141 144 147 150
    y_dist         (y) int64 -100 -97 -94 -91 -88 -85 -82 ... 83 86 89 92 95 98
    pressure       (z) int64 1000 925 850 700 500 300 250
    forecast_time  (time) datetime64[ns] 2022-08-10T22:00:00 ... 2022-08-11T1...
Dimensions without coordinates: time, z, y, x
Attributes:
    units:    Kelvin

We're going to start by adding some global attribute metadata. These are recommendations from the standard (not required), but they're easy to add and help users keep the data straight, so let's go ahead and do it.

In [32]:
ds.attrs['Conventions'] = 'CF-1.7'
ds.attrs['title'] = 'Forecast model run'
ds.attrs['nc.institution'] = 'Unidata'
ds.attrs['source'] = 'WRF-1.5'
ds.attrs['history'] = str(datetime.utcnow()) + ' Python'
ds.attrs['references'] = ''
ds.attrs['comment'] = ''
ds

<xarray.Dataset>
Dimensions:        (time: 13, z: 7, y: 67, x: 101)
Coordinates:
    x_dist         (x) int64 -150 -147 -144 -141 -138 ... 138 141 144 147 150
    y_dist         (y) int64 -100 -97 -94 -91 -88 -85 -82 ... 83 86 89 92 95 98
    pressure       (z) int64 1000 925 850 700 500 300 250
    forecast_time  (time) datetime64[ns] 2022-08-10T22:00:00 ... 2022-08-11T1...
Dimensions without coordinates: time, z, y, x
Data variables:
    temperature    (time, z, y, x) float64 0.3197 0.6291 ... -1.149 -0.4101
Attributes:
    Conventions:     CF-1.7
    title:           Forecast model run
    nc.institution:  Unidata
    source:          WRF-1.5
    history:         2022-08-10 06:42:12.578926 Python
    references:      
    comment:

We can also add attributes to this variable to define metadata. The CF conventions require a `units` attribute to be set for all variables that represent a dimensional quantity. The value of this attribute needs to be parsable by the UDUNITS library. Here we have already set it to a value of `'Kelvin'`. We also set the standard (optional) attributes of `long_name` and `standard_name`. The former contains a longer description of the variable, while the latter comes from a controlled vocabulary in the CF conventions. This allows users of data to understand, in a standard fashion, what a variable represents. If we had missing values, we could also set the `missing_value` attribute to an appropriate value.

> **NASA Dataset Interoperability Recommendations:**
>
> Section 2.2 - Include Basic CF Attributes
>
> Include where applicable: `units`, `long_name`, `standard_name`, `valid_min` / `valid_max`, `scale_factor` / `add_offset` and others.

In [33]:
ds.temperature.attrs['standard_name'] = 'air_temperature'
ds.temperature.attrs['long_name'] = 'Forecast air temperature'
ds.temperature.attrs['missing_value'] = -9999
ds.temperature

<xarray.DataArray 'temperature' (time: 13, z: 7, y: 67, x: 101)>
array([[[[ 0.31966001,  0.62911162,  1.46810581, ...,  0.87515276,
           0.31693765, -0.68455809],
         [ 0.18986965,  0.01840196,  1.42289809, ...,  0.82252125,
          -0.44852218,  0.45830285],
         [-0.59097526,  0.67670655,  1.28691167, ..., -0.23353007,
          -0.03685726,  0.06015763],
         ...,
         [-0.63314104,  1.0627754 ,  0.76806859, ..., -0.37088478,
          -0.1820268 , -0.89601011],
         [-0.8514717 ,  0.49759853, -1.12691574, ...,  0.70800531,
          -0.34981368,  0.40066832],
         [-0.46439381,  0.47530233,  1.18097279, ...,  0.7524677 ,
           0.06313997, -0.1427309 ]],

        [[-0.02283303, -0.09144041,  0.35689833, ...,  0.8239916 ,
           0.60545492, -0.51333928],
         [-0.99362739,  0.72566439,  0.83466609, ..., -1.32078148,
          -0.55641567,  0.80690797],
         [ 0.52498174,  0.29974021,  0.06959481, ...,  0.10632035,
          -0.01577078,  1.26781419],
...
         [-0.19166111,  1.13783231,  1.14830719, ...,  0.34927999,
           0.45713195, -1.48592946],
         [-1.30322075,  2.51739149,  0.81694123, ..., -0.39033119,
           0.62674055,  0.69432544],
         [ 0.1550955 ,  0.12162957,  0.14695446, ..., -0.16959999,
          -0.86542189,  0.02134799]],

        [[ 0.71655814, -1.99119425, -0.71171304, ..., -1.47766572,
          -1.0972982 ,  0.35227179],
         [ 0.51066693, -1.53859285, -1.57714262, ...,  0.71107797,
          -0.26561326,  1.24525168],
         [-0.31004721,  1.92040077, -1.16576846, ..., -0.69747617,
          -0.23262293,  1.02725806],
         ...,
         [ 1.53972641,  0.84477318, -0.25037428, ..., -2.16029206,
           1.70965877, -0.68985913],
         [ 0.32478888,  0.93460854, -0.96472961, ..., -0.43821734,
          -1.37024211, -0.2646514 ],
         [-0.25799393,  0.57621673,  2.0516006 , ...,  0.18359132,
          -1.1489152 , -0.41011924]]]])
Coordinates:
    x_dist         (x) int64 -150 -147 -144 -141 -138 ... 138 141 144 147 150
    y_dist         (y) int64 -100 -97 -94 -91 -88 -85 -82 ... 83 86 89 92 95 98
    pressure       (z) int64 1000 925 850 700 500 300 250
    forecast_time  (time) datetime64[ns] 2022-08-10T22:00:00 ... 2022-08-11T1...
Dimensions without coordinates: time, z, y, x
Attributes:
    units:          Kelvin
    standard_name:  air_temperature
    long_name:      Forecast air temperature
    missing_value:  -9999

### Coordinate variables

To properly orient our data in time and space, we need to go beyond dimensions (which define common sizes and alignment) and include values along these dimensions, which are called "Coordinate Variables". Generally, these are defined by creating a one dimensional variable with the same name as the respective dimension.

To start, we define variables which define our `x` and `y` coordinate values. These variables include `standard_name`s which allow associating them with projections (more on this later) as well as an optional `axis` attribute to make clear what standard direction this coordinate refers to.

In [34]:
ds.x.attrs['axis'] = 'X' # Optional
ds.x.attrs['standard_name'] = 'projection_x_coordinate'
ds.x.attrs['long_name'] = 'x-coordinate in projected coordinate system'

ds.y.attrs['axis'] = 'Y' # Optional
ds.y.attrs['standard_name'] = 'projection_y_coordinate'
ds.y.attrs['long_name'] = 'y-coordinate in projected coordinate system'

We also define a coordinate variable `pressure` to reference our data in the vertical dimension. The `standard_name` of `'air_pressure'` is sufficient to identify this coordinate variable as the vertical axis, but let's go ahead and specify the `axis` as well. We also specify the attribute `positive` to indicate whether the variable increases when going up or down. In the case of pressure, this is technically optional.

In [35]:
ds.pressure.attrs['axis'] = 'Z'  # Optional
ds.pressure.attrs['standard_name'] = 'air_pressure'
ds.pressure.attrs['positive'] = 'down'  # Optional

In [36]:
ds.forecast_time['axis'] = 'T'  # Optional
ds.forecast_time['standard_name'] = 'time'  # Optional
ds.forecast_time['long_name'] = 'time'

### Auxilliary Coordinates

Our data are still not CF-compliant because they do not contain latitude and longitude information, which is needed to properly locate the data. To solve this, we need to add variables with latitude and longitude. These are called "auxillary coordinate variables", not because they are extra, but because they are not simple one dimensional variables.

Below, we first generate longitude and latitude values from our projected coordinates using the `pyproj` library.

In [37]:
from pyproj import Proj
X, Y = np.meshgrid(x, y)
lcc = Proj({'proj':'lcc', 'lon_0':-105, 'lat_0':40, 'a':6371000.,
            'lat_1':25})
lon, lat = lcc(X * 1000, Y * 1000, inverse=True)

Now we can create the needed variables. Both are dimensioned on `y` and `x` and are two-dimensional. The longitude variable is identified as actually containing such information by its required units of `'degrees_east'`, as well as the optional `'longitude'` `standard_name` attribute. The case is the same for latitude, except the units are `'degrees_north'` and the `standard_name` is `'latitude'`.

In [38]:
ds = ds.assign_coords(lon = (['y', 'x'], lon))
ds = ds.assign_coords(lat = (['y', 'x'], lat))
ds

<xarray.Dataset>
Dimensions:        (time: 13, z: 7, y: 67, x: 101)
Coordinates:
    x_dist         (x) int64 -150 -147 -144 -141 -138 ... 138 141 144 147 150
    y_dist         (y) int64 -100 -97 -94 -91 -88 -85 -82 ... 83 86 89 92 95 98
    pressure       (z) int64 1000 925 850 700 500 300 250
    forecast_time  (time) datetime64[ns] 2022-08-10T22:00:00 ... 2022-08-11T1...
    lon            (y, x) float64 -106.6 -106.6 -106.5 ... -103.5 -103.4 -103.4
    lat            (y, x) float64 39.18 39.18 39.18 39.18 ... 40.79 40.79 40.79
Dimensions without coordinates: time, z, y, x
Data variables:
    temperature    (time, z, y, x) float64 0.3197 0.6291 ... -1.149 -0.4101
Attributes:
    Conventions:     CF-1.7
    title:           Forecast model run
    nc.institution:  Unidata
    source:          WRF-1.5
    history:         2022-08-10 06:42:12.578926 Python
    references:      
    comment:

In [39]:
ds.lon.attrs['units'] = 'degrees_east'
ds.lon.attrs['standard_name'] = 'longitude'  # Optional
ds.lon.attrs['long_name'] = 'longitude'

ds.lat.attrs['units'] = 'degrees_north'
ds.lat.attrs['standard_name'] = 'latitude'  # Optional
ds.lat.attrs['long_name'] = 'latitude'

With the variables created, we identify these variables as containing coordinates for the `Temperature` variable by setting the `coordinates` value to a space-separated list of the names of the auxilliary coordinate variables:

In [40]:
ds

<xarray.Dataset>
Dimensions:        (time: 13, z: 7, y: 67, x: 101)
Coordinates:
    x_dist         (x) int64 -150 -147 -144 -141 -138 ... 138 141 144 147 150
    y_dist         (y) int64 -100 -97 -94 -91 -88 -85 -82 ... 83 86 89 92 95 98
    pressure       (z) int64 1000 925 850 700 500 300 250
    forecast_time  (time) datetime64[ns] 2022-08-10T22:00:00 ... 2022-08-11T1...
    lon            (y, x) float64 -106.6 -106.6 -106.5 ... -103.5 -103.4 -103.4
    lat            (y, x) float64 39.18 39.18 39.18 39.18 ... 40.79 40.79 40.79
Dimensions without coordinates: time, z, y, x
Data variables:
    temperature    (time, z, y, x) float64 0.3197 0.6291 ... -1.149 -0.4101
Attributes:
    Conventions:     CF-1.7
    title:           Forecast model run
    nc.institution:  Unidata
    source:          WRF-1.5
    history:         2022-08-10 06:42:12.578926 Python
    references:      
    comment:

### Coordinate System Information

With our data specified on a Lambert conformal projected grid, it would be good to include this information in our metadata. We can do this using a "grid mapping" variable. This uses a dummy scalar variable as a namespace for holding all of the required information. Relevant variables then reference the dummy variable with their `grid_mapping` attribute.

Below we create a variable and set it up for a Lambert conformal conic projection on a spherical earth. The `grid_mapping_name` attribute describes which of the CF-supported grid mappings we are specifying. The names of additional attributes vary between the mappings.

In [41]:
ds['lambert_projection'] = int()
ds.lambert_projection.attrs['grid_mapping_name'] = 'lambert_conformal_conic'
ds.lambert_projection.attrs['standard_parallel'] = 25.
ds.lambert_projection.attrs['latitude_of_projection_origin'] = 40.
ds.lambert_projection.attrs['longitude_of_central_meridian'] = -105.
ds.lambert_projection.attrs['semi_major_axis'] = 6371000.0
ds.lambert_projection

<xarray.DataArray 'lambert_projection' ()>
array(0)
Attributes:
    grid_mapping_name:              lambert_conformal_conic
    standard_parallel:              25.0
    latitude_of_projection_origin:  40.0
    longitude_of_central_meridian:  -105.0
    semi_major_axis:                6371000.0

Now that we created the variable, all that's left is to set the `grid_mapping` attribute on our `Temperature` variable to the name of our dummy variable:

In [42]:
ds.temperature.attrs['grid_mapping'] = 'lambert_projection'  # or proj_var.name
ds

<xarray.Dataset>
Dimensions:             (time: 13, z: 7, y: 67, x: 101)
Coordinates:
    x_dist              (x) int64 -150 -147 -144 -141 -138 ... 141 144 147 150
    y_dist              (y) int64 -100 -97 -94 -91 -88 -85 ... 83 86 89 92 95 98
    pressure            (z) int64 1000 925 850 700 500 300 250
    forecast_time       (time) datetime64[ns] 2022-08-10T22:00:00 ... 2022-08...
    lon                 (y, x) float64 -106.6 -106.6 -106.5 ... -103.4 -103.4
    lat                 (y, x) float64 39.18 39.18 39.18 ... 40.79 40.79 40.79
Dimensions without coordinates: time, z, y, x
Data variables:
    temperature         (time, z, y, x) float64 0.3197 0.6291 ... -1.149 -0.4101
    lambert_projection  int64 0
Attributes:
    Conventions:     CF-1.7
    title:           Forecast model run
    nc.institution:  Unidata
    source:          WRF-1.5
    history:         2022-08-10 06:42:12.578926 Python
    references:      
    comment:

### Write to NetCDF

Xarray has built-in support for a few flavors of netCDF. Here we'll write a netCDF4 file from our Dataset.

In [43]:
ds.to_netcdf('test_netcdf.nc', format='NETCDF4')

In [44]:
!ncdump test_netcdf.nc

/bin/bash: ncdump: command not found
